" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')

" Any valid git URL is allowed
Plug 'https://github.com/tpope/vim-commentary.git'
Plug 'https://github.com/tpope/vim-sensible.git'
Plug 'https://github.com/tpope/vim-surround.git'
Plug 'https://github.com/tpope/vim-fugitive.git'
Plug 'https://github.com/ctrlpvim/ctrlp.vim.git'
Plug 'https://github.com/tpope/vim-sleuth.git'
Plug 'vim-perl/vim-perl', { 'for': 'perl', 'do': 'make clean carp dancer highlight-all-pragmas moose test-more try-tiny' }
Plug 'altercation/vim-colors-solarized'
Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'


" Initialize plugin system
call plug#end()

let g:solarized_termtrans = 1 " This gets rid of the grey background
" colorscheme solarized
autocmd BufNewFile,BufRead Rexfile  set ft=perl
autocmd BufNewFile,BufRead *.sls set ft=yaml

set bg=light
map <C-n> :NERDTreeToggle<CR>
let g:airline_theme='solarized'
